### ISSUE TITLE
breaking change

### ISSUE THREAD

**Issue by sineptic** [iruzo/simplex#5]
in new 5.8 version SimpleX update themes.

**Comment by iruzo** [comment]
Hey @sineptic,

Thanks a lot for notifying me, as soon as I have a moment, I will check out the new version and updates the themes.

**Comment by sineptic** [comment]
I want try  make it(catppuccin theme). Where  guidance located? I know only where palette, but where are how to apply it?

**Comment by iruzo** [comment]
Hi @sineptic,

You have a guide on how to apply the themes here: https://github.com/catppuccin/simplex?tab=readme-ov-file#usage

Follow the steps on the **Usage** section.

**Comment by iruzo** [comment]
I updated the colors to match the new version, thanks for opening the issue @sineptic !

**Comment by sineptic** [comment]
1 problem

**Comment by sineptic** [comment]
![Screenshot_20240625_224148_SimpleX.jpg](https://github.com/catppuccin/simplex/assets/98404983/c326bebe-c530-46d8-9688-9e3838ff8619)
